/**
 *
 * SettingsScene Container
 *
 */

import React from 'react';
import PropTypes from 'prop-types';
// import { Actions } from 'react-native-router-flux';
import { compose } from 'redux';
import { connect } from 'react-redux';
import {
  Container,
  Content,
  Text,
  View,
} from 'native-base';

import AppHeader from 'components/AppHeader';

import styles from './styles';

export class SettingsScene extends React.Component { // eslint-disable-line
  // constructor(props) {
  //   super(props);
  //   this.state = {
  //   };
  // }
  //
  // componentWillMount() {
  // }
  //
  // componentWillReceiveProps(nextProps) {
  // }
  //
  // componentDidMount() {
  // }
  //
  // componentWillUnmount() {
  // }

  // onClick = () => {
  // }

  render() {
    const { test } = this.props;
    return (
      <Container>
        <AppHeader title="Settings Scene" />

        <Content
          contentContainerStyle={styles.contentContainer}
          style={styles.content}
        >
          <View style={styles.contentView}>
            <Text style={styles.generateText}>{test}</Text>
            <Text style={styles.generateText}>This page is generated by the generator</Text>
            <Text style={styles.generateText}>此页面由生成器生成</Text>
          </View>
        </Content>
      </Container>
    );
  }
}

SettingsScene.defaultProps = {
  test: '',
};

SettingsScene.propTypes = {
  test: PropTypes.string,
};

const mapDispatchToProps = (dispatch) => ({
  dispatch,
});

const withConnect = connect(null, mapDispatchToProps);

export default compose(
  withConnect,
)(SettingsScene);
